### ISSUE TITLE
Moving sources to the root folder

### ISSUE THREAD

**Issue by thopiekar** [porjo/mt7601#10]
As this repository hosts most of all the mt7601 sources, what about moving all files from the /src folder to the root "/"?
Additionally why is there a patch this available while it is already applied?

(By the way: Based on my work I made now a dkms package of that driver, so it can now be savely installed/uninstalled on Debian/Ubuntu :smile: )

**Comment by porjo** [comment]
> what about moving all files from the /src

I'd prefer to keep original source code plus any modifications in it's own folder.

> Additionally why is there a patch this available while it is already applied?

Do you mean, why is the patch file included in the root folder?  The first commit does not show the changes made by the patch - it only shows changes after that - so I thought it would be good to keep the patch file in case anyone was interested.

**Comment by thopiekar** [comment]
Oh ok. Well, I had preferred to move all src/* files to root, as it is the most interesting content of the repo and most people probably didn't care, eg. about the patch.
