### ISSUE TITLE
Adding PPA to Readme.md

### ISSUE THREAD

**Issue by thopiekar** [porjo/mt7601#11]
You probably want to add this PPA to the docs.
Btw. this PPA should work with all debian distributions and debian itself. It just depends on the used kernel whether DKMS gets it built or not.

https://code.launchpad.net/~thopiekar/+archive/ubuntu/mt7601

**Comment by thopiekar** [comment]
btw. made a automated build against older mainline kernel versions:
mt7601, 3.0.0.4, 3.1.10-030110-generic, i686: installed
mt7601, 3.0.0.4, 3.2.66-030266-generic, i686: installed
mt7601, 3.0.0.4, 3.3.8-030308-generic, i686: installed
mt7601, 3.0.0.4, 3.4.105-0304105-generic, i686: installed
mt7601, 3.0.0.4, 3.5.7-03050733-generic, i686: installed
mt7601, 3.0.0.4, 3.6.11-030611-generic, i686: installed
mt7601, 3.0.0.4, 3.7.10-030710-generic, i686: installed
mt7601, 3.0.0.4, 3.8.13-03081328-generic, i686: installed
mt7601, 3.0.0.4, 3.9.11-030911-generic, i686: installed
mt7601, 3.0.0.4, 3.10.65-031065-generic, i686: installed
mt7601, 3.0.0.4, 3.11.10-03111015-generic, i686: installed
mt7601, 3.0.0.4, 3.12.37-031237-generic, i686: installed
mt7601, 3.0.0.4, 3.13.11-03131111-generic, i686: installed
mt7601, 3.0.0.4, 3.14.31-031431-generic, i686: installed
mt7601, 3.0.0.4, 3.15.10-031510-generic, i686: installed
mt7601, 3.0.0.4, 3.16.7-031607-generic, i686: installed
mt7601, 3.0.0.4, 3.17.8-031708-generic, i686: installed
mt7601, 3.0.0.4, 3.18.0-12-generic, i686: installed
mt7601, 3.0.0.4, 3.18.0-9-generic, i686: installed

Haven't tested them but I think/hope most of them will work on those kernels as they get built.

**Comment by porjo** [comment]
@thopiekar I'm not sure if English is your first language, but you should know that saying "You probably want to add this PPA to the docs." could be misinterpreted as being bossy or pushy. A nicer way to phrase that would be "I have created this, feel free to link to it". Another courtesy would be to link back to this repository from your page first, before requesting a link to yours. Please also include a credit to Mediatek and a reference to the GPLv2 license on your page.

**Comment by porjo** [comment]
I've updated the README now. Thanks for your contribution.

**Comment by fonini** [comment]
@thopiekar Hi, does this PPA works on Raspberry PI?

**Comment by thopiekar** [comment]
No, the PPA is configured (by default) to contain packages for i386 and amd64.
But: You can go to https://code.launchpad.net/~thopiekar/+archive/ubuntu/mt7601/+packages and select the latest package for a Ubuntu release (doesn't matter for which one, all the packages contain the same files).
E.g. the most recent package is https://code.launchpad.net/~thopiekar/+archive/ubuntu/mt7601/+files/mt7601-sta-dkms_3.0.0.4-0%7E201502011001%7Erev19%7Epkg2%7Eubuntu14.10.1_all.deb (Ubuntu Utopic). Download this file to you RPi, install it via ```dpkg -i <pkg>.deb``` and install missing dependencies (which might be at least dkms) via ```apt-get install -f``` (both command via root aka ```sudo <cmd>```).

Hope it will work for you :smiley:

**Comment by fonini** [comment]
Thanks, @thopiekar. I'll try this.
