### ISSUE TITLE
raspbian compiling error

### ISSUE THREAD

**Issue by ZiTAL** [porjo/mt7601#16]
```
$ make
make -C tools
make[1]: Entering directory '/usr/src/mt7601/src/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory '/usr/src/mt7601/src/tools'
/usr/src/mt7601/src/tools/bin2h
cp -f os/linux/Makefile.6 /usr/src/mt7601/src/os/linux/Makefile
make -C /lib/modules/3.18.0-trunk-rpi/build SUBDIRS=/usr/src/mt7601/src/os/linux modules
make[1]: Entering directory '/usr/src/linux-headers-3.18.0-trunk-rpi'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
  CC [M]  /usr/src/mt7601/src/os/linux/../../os/linux/rt_profile.o
cc1: error: invalid parameter ‘allow-store-data-races’
/usr/src/linux-headers-3.18.0-trunk-common/scripts/Makefile.build:262: recipe for target '/usr/src/mt7601/src/os/linux/../../os/linux/rt_profile.o' failed
make[4]: *** [/usr/src/mt7601/src/os/linux/../../os/linux/rt_profile.o] Error 1
/usr/src/linux-headers-3.18.0-trunk-common/Makefile:1398: recipe for target '_module_/usr/src/mt7601/src/os/linux' failed
make[3]: *** [_module_/usr/src/mt7601/src/os/linux] Error 2
Makefile:145: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.18.0-trunk-rpi'
Makefile:394: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2
```
```
$ uname -r
3.18.0-trunk-rpi
```
In ubuntu works perfect, but in raspbian i have this error :(

**Comment by ZiTAL** [comment]
changed kernel version to: 3.12-1-rpi and i compile it :)

**Comment by skarr** [comment]
I had no problems compiling the kernel module against the [latest rpi-3.18.y branch](https://github.com/raspberrypi/linux/tree/690878e23a8b7a7625514da6d9b005b5c7d178b3) under Ubuntu/Linaro on my Pi model B V2.
```
linaro@raspberry:~/Downloads/mt7601/src$ uname -r
3.18.5-v7+
linaro@raspberry:~/Downloads/mt7601/src$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:        14.10
Codename:       utopic
linaro@raspberry:~/Downloads/mt7601/src$ cat /proc/cpuinfo | grep -i model
model name      : ARMv7 Processor rev 5 (v7l)
model name      : ARMv7 Processor rev 5 (v7l)
model name      : ARMv7 Processor rev 5 (v7l)
model name      : ARMv7 Processor rev 5 (v7l)
linaro@raspberry:~/Downloads/mt7601/src$ gcc --version
gcc-4.8 (Ubuntu/Linaro 4.8.3-12ubuntu3) 4.8.3
linaro@raspberry:~/Downloads/mt7601/src$ md5sum os/linux/mt7601Usta.ko
27f6991dcff9ee19ba56e205f51ff4ef  os/linux/mt7601Usta.ko
```

I will try Rasbian tomorrow, [others have had success with Rasbian](http://www.raspberrypi.org/forums/viewtopic.php?f=28&t=98913) and [even more here](http://www.raspberrypi.org/forums/viewtopic.php?f=28&t=49864&start=175)

Remember to test with `insmod` before doing `make install`

**Comment by ZiTAL** [comment]
i'll check it tonight, thank you

**Comment by ZiTAL** [comment]
solved installing gcc-4.8:
```
aptitude install gcc-4.8 g++-4.8
rm -rf /usr/bin/gcc
rm -rf /usr/bin/g++
ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
ln -s /usr/bin/g++-4.8 /usr/bin/g++
```

**Comment by emiscience** [comment]
@ZiTAL Instead of deleting gcc/g++, just edit the config.mk e.g. os/linux/config.mk

218: CC := $(CROSS_COMPILE)gcc

change that to:

CC := $(CROSS_COMPILE)gcc-48

**Comment by ecardoz** [comment]
I'm trying to compile, but, I got same problem: 

The bug is not reproducible, so it is likely a hardware or OS problem.
scripts/Makefile.build:257: recipe for target '/home/ecardoz/Descargas/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../sta/sta_cfg.o' failed
make[2]: *** [/home/ecardoz/Descargas/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../sta/sta_cfg.o] Error 1
Makefile:1393: recipe for target '_module_/home/ecardoz/Descargas/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux' failed
make[1]: *** [_module_/home/ecardoz/Descargas/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.18.0-23-rpi2'
Makefile:394: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2


I've a Raspberry Pi 2 running Ubuntu Mate with Linux kernel: 3.18.0-23-rpi2

suggest?

**Comment by ZiTAL** [comment]
gcc version?
linux headers?

**Comment by ecardoz** [comment]
That's how I solved:

I solved sudo apt-get install --reinstall linux-headers-generic build-essential  
tar xjf DPO_MT7601U_LinuxSTA_3.0.0.4_20130913.tar.bz2  
cd DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/  
patch -p0 < ~/(ADD THE PATH)/rt2870-mt7601Usta-kuid_t-kgid_t.patch  
make  
su -c 'mkdir -p /etc/Wireless/RT2870STA/'  
su -c 'cp RT2870STA.dat /etc/Wireless/RT2870STA/RT2870STA.dat'

Is very important update the code with the patch file!

**Comment by dspinellis** [comment]
Note that the change in `src/os/linux/config.mk` should be
```
CC := $(CROSS_COMPILE)gcc-4.8
```
rather than
```
CC := $(CROSS_COMPILE)gcc-48
```
