### ISSUE TITLE
unloading mt7601 module fails

### ISSUE THREAD

**Issue by MrEngman** [porjo/mt7601#17]
When I try to unload the mt7601Usta.ko module using command "sudo rmmod mt7601Usta" it fails with error "Error: Module mt7601Usta is in use". With all other wifi modules I have no problem unloading them if I want to.

Command lsmod shows 

    Module     Size   Used by
    mt7601Usta 638549 1

I think the issue is caused by the fact that it says it is used by another module but it does not show one. So is this a bug? Using other wifi modules always shows "Used by" as 0 (zero).

**Comment by kuba-moo** [comment]
mt7601Usta use count is increased by the interface being active. Make sure you kill wpa_supplicant, wicd etc. and ifconfig it down before unloading.

**Comment by MrEngman** [comment]
I don't use wpa_supplicant, wicd etc. just /etc/network/interfaces to configure network, and ifconfig wlan0 down fails.

    ifconfig wlan0 down
    SIOCSIFFLAGS: Operation not permitted

I tried "sudo ifdown wlan0", as I have 95-ralink.rule to set name to wlan0, and that made no difference. Takes the wifi down but still showed used by as 1. Only unplugging the wifi adaptor changed it to 0 and then I could unload the driver.

Why is it set up like this? All other wifi modules I use always show "used by" as 0 and can be unloaded as necessary.

**Comment by kuba-moo** [comment]
The driver increases it's use count by itself when device is opened, admittedly it's weird - that's one of the reasons why this driver is not part of Linux kernel. Still I'm pretty sure I can remove and load this driver when the device is connected. Can you post output of `ifconfig -a`?

**Comment by MrEngman** [comment]
After command "sudo ifdown wlan0"   "ifconfig -a" shows

    eth0      Link encap:Ethernet  HWaddr b8:27:eb:9e:f7:5a
              inet addr:192.168.16.18  Bcast:192.168.16.255  Mask:255.255.255.0
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:52988 errors:0 dropped:18 overruns:0 frame:0
              TX packets:9094 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:19896103 (18.9 MiB)  TX bytes:1247014 (1.1 MiB)
    
    lo        Link encap:Local Loopback
              inet addr:127.0.0.1  Mask:255.0.0.0
              UP LOOPBACK RUNNING  MTU:65536  Metric:1
              RX packets:0 errors:0 dropped:0 overruns:0 frame:0
              TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0
              RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
    
    wlan0     Link encap:Ethernet  HWaddr e8:94:f6:1a:73:14
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:1055107 errors:7 dropped:0 overruns:0 frame:0
              TX packets:9595 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:316015759 (301.3 MiB)  TX bytes:914697 (893.2 KiB)
    
and lsmod shows

    Module                  Size  Used by
    snd_bcm2835            21342  0
    snd_pcm                93100  1 snd_bcm2835
    snd_seq                61097  0
    snd_seq_device          7209  1 snd_seq
    snd_timer              23007  2 snd_pcm,snd_seq
    snd                    67211  5 snd_bcm2835,snd_timer,snd_pcm,snd_seq,snd_seq_device
    uio_pdrv_genirq         3666  0
    uio                     9897  1 uio_pdrv_genirq
    mt7601Usta            638549  1
    sg                     21787  0

**Comment by kuba-moo** [comment]
You can see in the flags of `wlan0` that it's up:
`UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1`
the `UP` must disappear to remove the driver.

**Comment by MrEngman** [comment]
OK. Can you suggest a command I can use to get it to remove UP?

**Comment by kuba-moo** [comment]
`ifconfig down` should do if all daemons are stopped as I said in the first message...

**Comment by MrEngman** [comment]
Tried  a number of different commands without success. Finally found the following worked

    sudo killall ifplugd
    sudo ifconfig wlan0 down

ifconfig -a no longer shows UP for wlan0 and lsmod shows "Used by" for mt7601Usta is now 0 (zero)

Thanks for your help. Probably time to close this issue now I suppose.

**Comment by kuba-moo** [comment]
Yes, please close the issue. Glad I could help :)
