### ISSUE TITLE
Raspberry Pi 2, module compiles, but failes to load

### ISSUE THREAD

**Issue by mvadu** [porjo/mt7601#18]
I am trying it on a Raspberry Pi 2 Model B. I took the latest code

    git clone --depth=1 https://github.com/raspberrypi/linux.git
    sudo ln -s /home/pi/src/kernel/linux /lib/modules/$(uname -r)/build
    gzip -dc /proc/config.gz > .config
    make oldconfig
    make prepare
    make modules_prepare
    wget https://github.com/raspberrypi/firmware/raw/master/extra/Module.symvers
    cd ~
    git clone https://github.com/porjo/mt7601
    cd mt7601/src
    make

Gives me

    make -C tools
    make[1]: Entering directory '/home/pi/git/mt7601/src/tools'
    gcc -g bin2h.c -o bin2h
    make[1]: Leaving directory '/home/pi/git/mt7601/src/tools'
    /home/pi/git/mt7601/src/tools/bin2h
    cp -f os/linux/Makefile.6 /home/pi/git/mt7601/src/os/linux/Makefile
    make -C /lib/modules/3.18.9-v7+/build SUBDIRS=/home/pi/git/mt7601/src/os/linux modules
    make[1]: Entering directory '/home/pi/src/linux'
      CC [M]  /home/pi/git/mt7601/src/os/linux/../../chips/mt7601.o
    /home/pi/git/mt7601/src/os/linux/../../chips/mt7601.c: In function ‘MT7601DisableTxRx’:
    /home/pi/git/mt7601/src/os/linux/../../chips/mt7601.c:1491:3: warning: ‘return’ with no value, in function returning non-void [-Wreturn-type]
    /home/pi/git/mt7601/src/os/linux/../../chips/mt7601.c: In function ‘MT7601_Init’:
    /home/pi/git/mt7601/src/os/linux/../../chips/mt7601.c:3387:24: warning: assignment from incompatible pointer type [enabled by default]
      LD [M]  /home/pi/git/mt7601/src/os/linux/mt7601Usta.o
      Building modules, stage 2.
      MODPOST 1 modules
    WARNING: "_raw_spin_lock_bh" [/home/pi/git/mt7601/src/os/linux/mt7601Usta.ko] undefined!
    WARNING: "del_timer_sync" [/home/pi/git/mt7601/src/os/linux/mt7601Usta.ko] undefined!
    WARNING: "_raw_spin_unlock_irqrestore" [/home/pi/git/mt7601/src/os/linux/mt7601Usta.ko] undefined!
    WARNING: "_raw_spin_unlock_bh" [/home/pi/git/mt7601/src/os/linux/mt7601Usta.ko] undefined!
    WARNING: "_raw_spin_lock_irqsave" [/home/pi/git/mt7601/src/os/linux/mt7601Usta.ko] undefined!
      CC      /home/pi/git/mt7601/src/os/linux/mt7601Usta.mod.o
      LD [M]  /home/pi/git/mt7601/src/os/linux/mt7601Usta.ko
    make[1]: Leaving directory '/home/pi/src/linux'
    cp -f /home/pi/git/mt7601/src/os/linux/mt7601Usta.ko /tftpboot 2>/dev/null || :

Now trying to install
      sudo insmod /home/pi/git/mt7601/src/os/linux/mt7601Usta.ko
      Error: could not insert module /home/pi/git/mt7601/src/os/linux/mt7601Usta.ko: Invalid module format

**Comment by kuba-moo** [comment]
I *think* it's because your installed kernel is different than the source. Please either build and use a kernel from the git source that you cloned *or* just install the appropriate kernel-something package (the kernel development package, I don't know what it's called for RPi and you don't specify the distro). Making a link in /home/pi/src/kernel/linux by hand is not a good idea.

**Comment by MrEngman** [comment]
I am able to compile and install OK on a Pi B2. Tried on all 3.18 versions of raspbian on Pi B+,  Pi A and Pi B2. Currently using 3.18.10-v7+ #775.

I have drivers for all versions of raspbian, currently 3.18.3 to 3.18.10, for all older versions of Pi and the new Pi B2.

Compiling on a Pi B2, however, creates a lot of warnings. Would be nice to fix them but I don't understand C code. Using gcc (Raspbian 4.8.4-1) 4.8.4

**Comment by ArthurJam** [comment]
Hi,
I am the same problem.

Error: could not insert module os/linux/mt7601Usta.ko: Invalid module format

I grab the source from github :
git clone https://github.com/raspberrypi/linux.git
sudo ln -s /usr/src/linux /lib/modules/`uname -r`/build

Do you have one idea ?

**Comment by kuba-moo** [comment]
Please read what I wrote above. You are using incompatible images and sources. Try installing the *linux-image-rpi2-rpfv* on RPi 2. I'm not an expert on Pi, but it looks like this package will install the newest kernel and all files necessary for compilation. Installing *linux-kbuild-3.18* may also work.

Creating links to the source by hand is **wrong**. Who gave all of you this idea?

**Comment by MrEngman** [comment]
@kuba-moo, why is creating links by hand wrong. I do it all the time, always have done, and have no problems. How else can I do it?

Those packages you mention are they downloaded by apt-get? If not how do I get hold of them. Just curious to see what they are.

@mvadu, @ArthurJam,  If you are compiling a module for the Pi B2 the Module.symvers for the Pi B2 is Module7.symvers in the git firmware repository so you should download Module7.symvers and rename it to Module.symvers. This is probably why your modules fail to load.

Have a look at the firmware repository and you will see files Module7.symvers, for Pi B2, and Module.symvers for all the other Pi's. e.g. https://github.com/raspberrypi/firmware/tree/3ea439ca4b6a84a06bb934347ecff6f7269f663c/extra

**Comment by kuba-moo** [comment]
I don't mean creating links in general. I mean in this particular case to drop in some random source in the place of the real source of the kernel. Every distribution has a package with the source that matches the binary kernel package. When you install that package with source the link will be created automatically and you are guaranteed that it will point to the right source. Do you know what I mean? I advise you to *not* download the source by hand and then link it, just find the package that will do it for you...

Yes, all the packages I mentioned are installed by apt-get.

**Comment by MrEngman** [comment]
I have seen various posts by people on the Raspberry Pi forum trying to install packages to get the kernel source to compile modules and so many have had problems. e.g. download a package and it appears to be the wrong version of source or various other problems. I've never tried this as I never really understood how to do it.

The way I use to compile my modules is I have cloned the kernel and firmware repositories on my Pi. I can then compile modules for any version of the kernel using git checkout commit-id on the linux and firmware directories to set the kernel and firmware to match the version I need. And keeping the sources up to date is easy with git pull. And, regardless of the kernel version I am compiling for, the linux source directory is in a fixed location so setting the build symlink is only required once unless I update the kernel my Pi is running when I may need to regenerate it if the version has changed.

**Comment by mvadu** [comment]
@MrEngman Thank you for that **Module7.symvers** part. I am trying it now. You also mentioned about firmware, are you pulling the whole [firmware git repo](https://github.com/raspberrypi/firmware)? Even the firmware has an Modules, how does it linked/related  to Linux/build/modules? It will be of great help if you could post your structure and build procedure here or on the Raspberry forum.

**Comment by ArthurJam** [comment]
Yes, thank you for the advice.
I use Module7.symvers and now the module can be loaded without errors.
But the lsmod command dont respond and freeze my console (and no new interface has been created).

**Comment by ArthurJam** [comment]
Ok sorry for this duplicate, I see the same issue in issue list.
I use gcc version 4.7:

sudo apt-get install gcc-4.7
sudo rm /usr/bin/gcc
sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc
...

No more errors when I use insmod.
Do you know how to get the interface in wpa_gui ?

**Comment by MrEngman** [comment]
@ArthurJam probably not the right place for this, however. 

Check command `ifconfig` to see if your wifi is showing and check the name being used, probably `ra0`

Check file `/etc/network/interfaces` which will probably be 
```
auto lo

iface lo inet loopback
iface eth0 inet dhcp

allow-hotplug wlan0
iface wlan0 inet manual
wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
iface default inet dhcp
```
Change the name `wlan0` to `ra0` and wpa_gui should then work after you reboot the Pi.

Or you can change the wifi name to `wlan0` by generating the file `/etc/udev/rules.d/95-ralink.rules` using command `sudo nano /etc/udev/rules.d/95-ralink.rules` and setting the contents to
```
ACTION=="add", SUBSYSTEM=="net", ATTR{type}=="1", KERNEL=="ra*", NAME="wlan0"
```
and then you do not need to change file `/etc/network/interfaces`. Reboot after making any changes to the files.

**Comment by mvadu** [comment]
Thanks you @kuba-moo @MrEngman , I finally got a hang of it.. I followed steps in https://sites.google.com/site/thepihacker/pimodules along with modifications
1. created a directory called src
2. did a git pull for [firmware](https://github.com/raspberrypi/firmware) and [Linux](https://github.com/raspberrypi/linux)
3. Edited Linux make file `EXTRAVERSION` with v7+
4. Updated gcc (had to follow (another guide) [https://somewideopenspace.wordpress.com/2014/02/28/gcc-4-8-on-raspberry-pi-wheezy/] to get gcc 4.8.4 on the Pi), and made that default compiler
5. Copied downloaded firmware boot and modules to /boot and /lib/modules folders
6. reboot
7.  `make oldconfig` & `make modules_prepare`
8. create a sym link to (`sudo ln -s /home/pi/src/kernel/linux /lib/modules/$(uname -r)/build`) sorry @kuba-moo  the mt7601 makefile uses pwd, so I could not copy the src folder inside my Linux/custom folder to get it compile
9. inside mt7601/src issue  `make`
10. Issue `insmod` 

All is well, and thank you all once again!

**Comment by blindpet** [comment]
@mvadu I'm having this same issue but on the B+. I've updated to gcc 4.8 and edited the EXTRAVERSION = + as in the pihacker guide but still get the Invalid module format. Would you mind slightly expanding your guide a bit with some detail, maybe there's something obvious I'm missing.

**Comment by mikhas-rock** [comment]
I have followed same procedures as @mvadu and I was able to successfully compile the module.

However, my rpi freezes when I run insmod. How can I diagnose that?

**Comment by mvadu** [comment]
@blindpet Did you copy right version of Module.symvers from firmware/extra to your Linux git folder? my literal steps were: (from my `~`)

    1. mkdir src
    2. cd src
    3. git clone --depth 1 https://github.com/raspberrypi/firmware
    4. git clone --depth 1 https://github.com/raspberrypi/linux
    5. cat firmware/extra/uname_string 
          Linux version 3.18.10+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #775 PREEMPT Thu Apr 2 18:10:12 BST 2015 in my case
    6. sudo nano linux/Makefile 
    7. Update EXTRAVERSION = v7+
    9. Update gcc
    8. sudo mkdir /boot/backup
    9. sudo cp /boot/* /boot/backup/
    10. sudo cp -r firmware/modules /lib
    11. sudo cp -r src/firmware/boot /
    12. sudo cp firmware/extra/Module7.symvers linux/Module.symvers
    13. sync
    14. sudo reboot
    15. cd src/
    16. sudo ln -s /home/pi/src/linux /lib/modules/$(uname -r)/build
    17. cd linux 
    18. sudo gunzip -c /proc/config.gz > .config
    19. sudo make oldconfig
    20. sudo make modules_prepare
    21. mkdir ~/git
    22. cd ~/git
    23. git clone https://github.com/porjo/mt7601
    24. cd src
    25. sudo make
    26. sudo insmod /home/pi/git/mt7601/src/os/linux/mt7601Usta.ko 
    27. lsmod | grep 7601

**Comment by blindpet** [comment]
@mvadu Thank you so much. I have spent so many hours on this and your guide worked. I only had to adjust the EXTRAVERSION to +v11 since I was on 3.18.11. For anybody that stumbles upon this you will want to take the uname -r output and use the last 3 characters to adjust the EXTRAVERSION value. Thank you again!

**Comment by mvadu** [comment]
awesome @blindpet , lets make the step #7 as `Update EXTRAVERSION = ` match output of `uname -r | cut -c9-12` that should be a genericstep working across different version of Pi's

**Comment by MrEngman** [comment]
Strange. I compile several different modules for both P2 and P1 and never have to edit the Makefile.

**Comment by mvadu** [comment]
Yes, I can confirm that too.. Today I compiled a module without editing Makefile, so `EXTRAVERSION` was empty, and module compiled successfully.

**Comment by mvadu** [comment]
Closing this issue as I am able to compile and use the driver on multiple revisions of Raspbian on Pi 2.

**Comment by wcypierre** [comment]
Raspberry Pi Model: B
GCC: 4.8.4
uname -r: 3.18.14+

So I've been following https://github.com/porjo/mt7601/issues/18#issuecomment-90389343's instructions and in the end when I tried to insmod, I still get the "Error: could not insert module os/linux/mt7601Usta.ko: Invalid module format" error.

What I've done(on a clean installation) before performing the steps above would be: 
1. Add the sources for gcc-4.8
2. apt-get update
3. apt-get install -t jessie gcc-4.8 g++-4.8
4. apt-get upgrade
5. rpi-update (which lead me to the kernel of 3.18.14+)

Any leads?

**Comment by issamy** [comment]
Hi all, 

I am also getting the insmod issue (no problem at compil), using a rapsberry pi 2. 
I did use the Module7.symvers (rename to Module.symvers ) also updated the EXTRAVERSION to v7+ (since my module -r returns 3.18.14-v7+). For info I al using gcc version 4.6.3
I have spent a couple of hours on this and I al seriously thinking of ordering another wifi dongle that works out of the box, so if you have any idea, please let me know
