### ISSUE TITLE
Cannot compile on Raspbian

### ISSUE THREAD

**Issue by Nayar** [porjo/mt7601#22]
I am having this issue

```
pi@raspberrypi ~/mt7601/src $ make
make -C tools
make[1]: Entering directory '/home/pi/mt7601/src/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory '/home/pi/mt7601/src/tools'
/home/pi/mt7601/src/tools/bin2h
cp -f os/linux/Makefile.6 /home/pi/mt7601/src/os/linux/Makefile
make -C /lib/modules/3.18.7+/build SUBDIRS=/home/pi/mt7601/src/os/linux modules
make[1]: *** /lib/modules/3.18.7+/build: No such file or directory.  Stop.
Makefile:394: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2
```

**Comment by kuba-moo** [comment]
I'm not sure there is a build for 3.18.7+. Can you try installing **linux-image-3.18.0-trunk-rpi** and **linux-headers-3.18.0-trunk-rpi** (or *linux-image-3.18.0-trunk-rpi2* etc if you have RPi2) and then rebooting? This should install the RPi kernel together with appropriate directories.

**Comment by Nayar** [comment]
Did not solve it. Managed to install a driver with the following commands. Dunno what it does but it made it work.

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=104923&p=734210&hilit=mt7601#p734210

**Comment by mvadu** [comment]
See my instructions on #18

**Comment by porjo** [comment]
@Nayar is this still an issue for you? I will close this issue now. It can be reopened if necessary.
