### ISSUE TITLE
News: MT7601 now in upstream

### ISSUE THREAD

**Issue by thopiekar** [porjo/mt7601#27]
Would be great to add to the readme that there is upstream support for MT7601 in kernel 4.2

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/net/wireless/mediatek/Kconfig?id=c869f77d6abb5d5f9f2f1a661d5c53862a9cad34

**Comment by porjo** [comment]
The readme already says this.

Once 4.2 is released as stable, I'll put a prominent notice on the frontpage alerting people that this driver is deprecated.
