### ISSUE TITLE
Failed To Activate connection (32) The connection's MAC address did not match this device.

### ISSUE THREAD

**Issue by holy008** [porjo/mt7601#28]
Success using this driver to connect as client mode.
But when I use this as AP mode, I got error Failed To Activate Connection (32) The connection's MAC address did not match this device.
I am desprate to search the solution.
Can anybody help me?

Thx very much

**Comment by holy008** [comment]
I found solution for my problem at [this link](https://kenelm1985.wordpress.com/2015/05/06/%E9%A8%B0%E8%A8%8A%E5%85%A8%E6%B0%91wifi-360-%E9%9A%A8%E8%BA%AB-wifi-%E7%AC%AC%E4%BA%8C%E4%BB%A3-%E5%B0%8F%E7%B1%B3%E9%9A%A8%E8%BA%AB-wifi-%E5%B0%8F%E5%BA%A6-wifi-linux-ap%E6%A8%A1%E5%BC%8F/).

I hope can help anybody with same problem.

regards,
ANDI

**Comment by porjo** [comment]
FYI to anyone looking, the solution linked above involves building a driver using source code from another repository: https://github.com/eywalink/mt7601u

**Comment by porjo** [comment]
Thanks @holy008 for the information
