### ISSUE TITLE
kernel 4.0.9 i386 RX keeps dropping to 1mbs

### ISSUE THREAD

**Issue by mantheman** [porjo/mt7601#29]
Hi. I prefer to use this driver because it performs much much better than the new driver. But my problem is that the RX rate keeps dropping to 1mbs all the time for a couple of seconds, meaning that for streaming videos on the internet, is almost impossible (espescially with live streaming where normally don't buffer that much) I haven't tested with other kernels. My connection otherwise is almost perfect. TX rate stays at 150mbs and iwconfig show signal quality as 147-150/150.

The new driver doesnt drop to 1mbs but it is unstable, and much slower. Transferring a large file over samba will make the driver timeout and I'll have to start all over. 

Is there a hack somehow to disable it dropping to 1mbs? I'lve looked at the source, but I'm not skilled enough to figure it out by myself.

**Comment by mantheman** [comment]
This doesn't seem to be a problem when utilizing the full bandwidth of the dongle. Transferring to the dongle via samba seldom sees the speed drop, and I get a very steady avg of 11MB/s. When I pause the transfer, I  can see in the webif of my router that the RX drops to 1mbs, and I if unpause the transfer at the right moment there is also a slight hiccup before the RX speed returns to normal.

This is so bad that I often have problems keeping a SSH session open. The driver  is very good, apart from this.

**Comment by mantheman** [comment]
Tried to upgrade to kernel 4.1.6, and performance is worse. Max bitrate for tx/rx is now 54 instead of 150.  Rx still drops to 1mbs frequently, perhaps even moreso. So i guess for the time being this driver is best for older kernels. Possibly 3.19.x or less.

**Comment by porjo** [comment]
FYI, kernel 4.2 is now stable. It includes an mt7601u driver. I recommend trying to use that instead.

**Comment by mantheman** [comment]
Thx, i've already moved on to the mt7601u driver. It not as bad as my first impression was, but it gives less than half the speed of this driver. Even so, it's more stable and doesnt suddenly drop to 1Mbs/RX (which really translates to full stop).
