### ISSUE TITLE
Problem installing on version 4.1.6-v7+ #810

### ISSUE THREAD

**Issue by LeoYong95** [porjo/mt7601#32]
Hi Porjo,

I am trying to install this driver for my Raspberry Pi but I am facing Problems.

I am using Raspberry Pi 2 Model B 1GB;

The output for <code>uname -a</code> is,
<code>Linux Raspberrypi 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15: 32: 12 BST 2015 armv7l GNU/Linux</coode>

I have cloned the repository, but when I run <code>make</code> I got these error messages.
<code>make -C /lib/modules/`uname-r`/build M=$PWD </code>

<code>make[1]: *** /lib/modules/4.1.6-v7+/build: No such file or directory.     Stop. </code>

<code>Makefile:8: recipe for target 'default' failed </code>

<code>make: *** [default] Error 2  </code>

Why do I get this error messages? Thank you so much for your time replying this.

**Comment by porjo** [comment]
Try the solution suggested here:
https://www.raspberrypi.org/forums/viewtopic.php?t=67347&p=495080

**Comment by LeoYong95** [comment]
Thank you so much,

I followed the instruction on it and fixed the problem while executing the command 
<code>make</code>.

but when I tried to insert module using <code>insmod</code>

there is an error stating the format of module is invalid.

I googled a bit and found  [this](https://github.com/porjo/mt7601/issues/18). I followed the step by step instruction and I can't <code>make oldconfig</code> 

When I was executing <code>make oldconfig</code>, there is a bunch of questions pooped up and I don't understand the question.

I really don't know what is wrong here. 

Thanks again for your help on this.

**Comment by porjo** [comment]
@LeoYong95 if you need the driver to work urgently, you may need to compile your own kernel from source - see https://www.raspberrypi.org/documentation/linux/kernel/building.md . Get the source from here: https://github.com/raspberrypi/linux/tree/rpi-4.2.y

Otherwise, the official rpi kernel should be updating to 4.2. within the next month.

**Comment by porjo** [comment]
@LeoYong95 I see that mt7601u driver from kernel 4.2 [has been back-ported to 4.1](https://github.com/raspberrypi/linux/issues/1090#issuecomment-130615417)

This means that you should be able to use the official kernel driver without any compiling! Make sure you have the latest kernel (apt-get upgade). You will then need to [copy the firmware in place](https://github.com/raspberrypi/linux/issues/1090#issuecomment-137782875). Good luck.

**Comment by porjo** [comment]
Actually, I believe you need to issue `rpi-update` to upgrade your kernel on Raspberry pi distro (rather than `apt-get upgrade`)

**Comment by LeoYong95** [comment]
@porjo  thanks^^ I will try this later

**Comment by LeoYong95** [comment]
Hi there, Sry for the delay... I have update my kernel version to 4.1.7-v7+ #817 and I switch to a different kind of wifi adapter... DWA-131 E1. and It works out pretty well for me. 

Although I did not use mt7601 but thanks for helping me out in my problems.^^

**Comment by porjo** [comment]
@LeoYong95 if you can, please test with mt760u as other people may find the results interesting.

**Comment by LeoYong95** [comment]
ok^^ Thank you so much.

That module also work with this version of wifi adapter??
<code>Bus 001 Device 005: ID 148f:7601 Ralink Technology, Corp.</code>
