### ISSUE TITLE
Compiling error with Gentoo 3.17.7? 

### ISSUE THREAD

**Issue by pmam2** [porjo/mt7601#5]
Hi,
I am trying to install this USB dongle in my laptop and here are some info and the outputs with compiling error -
My kernel: uname -a
Linux mg_lap 3.17.7-gentoo #25 SMP Sat Jan 24 12:58:35 IST 2015 i686 Mobile Intel(R) Celeron(R) CPU 2.40GHz GenuineIntel GNU/Linux
Dongle info: Bus 001 Device 002: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter
I followed your commands and after 'make' I got this error:
```
scripts/Makefile.build:257: recipe for target '/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.o' failed
make[2]: *** [/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.o] Error 1
Makefile:1373: recipe for target '_module_/root/src/mt7601/src/os/linux' failed
make[1]: *** [_module_/root/src/mt7601/src/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-3.17.7-gentoo'
Makefile:394: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2 
```
Please adivse how can I fix this issue!
Regards

**Comment by porjo** [comment]
Is that the only output you see after issuing `make`? If there are other messages, please include them.

Also, try running the following commands (inside the `src` directory), and paste the output here

```
make clean
make -C tools
cp -f os/linux/Makefile.6 /root/src/mt7601/src/github/porjo/mt7601/src/os/linux/Makefile
make -C /lib/modules/3.17.7/build SUBDIRS=/root/src/mt7601/src/github/porjo/mt7601/src/os/linux modules
```

**Comment by pmam2** [comment]
Here the full make output:
 make
make -C tools
make[1]: Entering directory '/root/src/mt7601/src/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory '/root/src/mt7601/src/tools'
/root/src/mt7601/src/tools/bin2h
cp -f os/linux/Makefile.6 /root/src/mt7601/src/os/linux/Makefile
make -C /lib/modules/3.17.7-gentoo/build SUBDIRS=/root/src/mt7601/src/os/linux modules
make[1]: Entering directory '/usr/src/linux-3.17.7-gentoo'
  CC [M]  /root/src/mt7601/src/os/linux/../../os/linux/rt_profile.o
/root/src/mt7601/src/os/linux/../../os/linux/rt_profile.c: In function ‘announce_802_3_packet’:
/root/src/mt7601/src/os/linux/../../os/linux/rt_profile.c:331:16: warning: unused variable ‘pAd’ [-Wunused-variable]
  RTMP_ADAPTER *pAd = (RTMP_ADAPTER *)pAdSrc;
                ^
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/assoc.o
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/auth.o
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/auth_rsp.o
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/sync.o
/root/src/mt7601/src/os/linux/../../sta/sync.c: In function ‘MlmeForceJoinReqAction’:
/root/src/mt7601/src/os/linux/../../sta/sync.c:181:24: warning: unused variable ‘pInfo’ [-Wunused-variable]
  MLME_JOIN_REQ_STRUCT *pInfo = (MLME_JOIN_REQ_STRUCT *)(Elem->Msg);
                        ^
/root/src/mt7601/src/os/linux/../../sta/sync.c: In function ‘PeerBeacon’:
/root/src/mt7601/src/os/linux/../../sta/sync.c:2181:12: warning: passing argument 8 of ‘StaAddMacTableEntry’ from incompatible pointer type [enabled by default]
            ie_list->CapabilityInfo) == FALSE)
            ^
In file included from /root/src/mt7601/src/include/rt_config.h:59:0,
                 from /root/src/mt7601/src/os/linux/../../sta/sync.c:28:
/root/src/mt7601/src/include/rtmp.h:7892:9: note: expected ‘struct IE_LISTS *’ but argument is of type ‘struct BCN_IE_LIST *’
 BOOLEAN StaAddMacTableEntry(
         ^
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/sanity.o
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/rtmp_data.o
/root/src/mt7601/src/os/linux/../../sta/rtmp_data.c: In function ‘STAHandleRxDataFrame’:
/root/src/mt7601/src/os/linux/../../sta/rtmp_data.c:523:4: warning: passing argument 2 of ‘MacTableLookup’ from incompatible pointer type [enabled by default]
    pEntry = MacTableLookup(pAd, &pHeader->Addr2);
    ^
In file included from /root/src/mt7601/src/include/rt_config.h:59:0,
                 from /root/src/mt7601/src/os/linux/../../sta/rtmp_data.c:28:
/root/src/mt7601/src/include/rtmp.h:8429:18: note: expected ‘UCHAR *’ but argument is of type ‘UCHAR (*)[6]’
 MAC_TABLE_ENTRY *MacTableLookup(RTMP_ADAPTER *pAd, UCHAR *pAddr);
                  ^
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/connect.o
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/wpa.o
  CC [M]  /root/src/mt7601/src/os/linux/../../sta/sta_cfg.o
/root/src/mt7601/src/os/linux/../../sta/sta_cfg.c: In function ‘RtmpIoctl_rt_ioctl_siwfreq’:
/root/src/mt7601/src/os/linux/../../sta/sta_cfg.c:6011:6: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
      STRING ChStr[5] = {0};
      ^
/root/src/mt7601/src/os/linux/../../sta/sta_cfg.c: In function ‘RtmpIoctl_rt_ioctl_siwgenie’:
/root/src/mt7601/src/os/linux/../../sta/sta_cfg.c:7616:13: warning: assignment from incompatible pointer type [enabled by default]
     eid_ptr = pAd->StaCfg.pWpaAssocIe;
             ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/crypt_md5.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/crypt_sha2.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/crypt_hmac.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/crypt_aes.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/crypt_arc4.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/mlme.o
/root/src/mt7601/src/os/linux/../../common/mlme.c: In function ‘AsicRxAntEvalTimeout’:
/root/src/mt7601/src/os/linux/../../common/mlme.c:5201:45: warning: unused variable ‘rssi_diff’ [-Wunused-variable]
  CHAR   larger = -127, rssi0, rssi1, rssi2, rssi_diff;
                                             ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_wep.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/action.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_data.o
/root/src/mt7601/src/os/linux/../../common/cmm_data.c: In function ‘dump_txinfo’:
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:172:27: warning: unused variable ‘pkt_txinfo’ [-Wunused-variable]
  struct _TXINFO_NMAC_PKT *pkt_txinfo = (struct _TXINFO_NMAC_PKT *)pTxInfo;
                           ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c: In function ‘CmdRspEventCallbackHandle’:
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:2509:8: warning: unused variable ‘Ret’ [-Wunused-variable]
  INT32 Ret;
        ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c: In function ‘StopDmaTx’:
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:2684:8: warning: unused variable ‘IdleNums’ [-Wunused-variable]
  UINT8 IdleNums = 0;
        ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:2682:20: warning: unused variable ‘UsbCfg’ [-Wunused-variable]
  USB_DMA_CFG_STRUC UsbCfg;
                    ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c: At top level:
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:102:15: warning: ‘txwi_txop_str’ defined but not used [-Wunused-variable]
 static UCHAR *txwi_txop_str[]={"HT_TXOP", "PIFS", "SIFS", "BACKOFF", "Invalid"};
               ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:156:15: warning: ‘txinfo_type_str’ defined but not used [-Wunused-variable]
 static UCHAR *txinfo_type_str[]={"PKT", "", "CMD", "RSV", "Invalid"};
               ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:157:15: warning: ‘txinfo_d_port_str’ defined but not used [-Wunused-variable]
 static UCHAR *txinfo_d_port_str[]={"WLAN", "CPU_RX", "CPU_TX", "HOST", "VIRT_RX", "VIRT_TX", "DROP", "Invalid"};
               ^
/root/src/mt7601/src/os/linux/../../common/cmm_data.c:158:15: warning: ‘txinfo_que_str’ defined but not used [-Wunused-variable]
 static UCHAR *txinfo_que_str[]={"MGMT", "HCCA", "EDCA_1", "EDCA_2", "Invalid"};
               ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/rtmp_init.o
/root/src/mt7601/src/os/linux/../../common/rtmp_init.c: In function ‘NICInitAsicFromEEPROM’:
/root/src/mt7601/src/os/linux/../../common/rtmp_init.c:981:9: warning: unused variable ‘i’ [-Wunused-variable]
  USHORT i;
         ^
/root/src/mt7601/src/os/linux/../../common/rtmp_init.c: In function ‘NICInitializeAdapter’:
/root/src/mt7601/src/os/linux/../../common/rtmp_init.c:1292:22: warning: unused variable ‘GloCfg’ [-Wunused-variable]
  WPDMA_GLO_CFG_STRUC GloCfg;
                      ^
/root/src/mt7601/src/os/linux/../../common/rtmp_init.c: In function ‘NICInitializeAsic’:
/root/src/mt7601/src/os/linux/../../common/rtmp_init.c:1367:11: warning: unused variable ‘KeyIdx’ [-Wunused-variable]
  USHORT   KeyIdx;
           ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/rtmp_init_inf.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_tkip.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_aes.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_sync.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/eeprom.o
/root/src/mt7601/src/os/linux/../../common/eeprom.c: In function ‘RtmpChipOpsEepromHook’:
/root/src/mt7601/src/os/linux/../../common/eeprom.c:34:9: warning: unused variable ‘e2p_csr’ [-Wunused-variable]
  UINT32 e2p_csr;
         ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_sanity.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_info.o
/root/src/mt7601/src/os/linux/../../common/cmm_info.c: In function ‘set_rf’:
/root/src/mt7601/src/os/linux/../../common/cmm_info.c:5730:3: warning: format ‘%x’ expects argument of type ‘unsigned int *’, but argument 5 has type ‘UCHAR *’ [-Wformat=]
   rv = sscanf(arg, "%d-%d-%x", &(bank_id), &(rf_id), &(rf_val));
   ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_cfg.o
/root/src/mt7601/src/os/linux/../../common/cmm_cfg.c: In function ‘wmode_valid_and_correct’:
/root/src/mt7601/src/os/linux/../../common/cmm_cfg.c:279:8: warning: unused variable ‘mode’ [-Wunused-variable]
  UCHAR mode = *wmode;
        ^
/root/src/mt7601/src/os/linux/../../common/cmm_cfg.c: At top level:
/root/src/mt7601/src/os/linux/../../common/cmm_cfg.c:203:16: warning: ‘BAND_STR’ defined but not used [-Wunused-variable]
 static PSTRING BAND_STR[] = {"Invalid", "2.4G", "5G", "2.4G/5G"};
                ^
/root/src/mt7601/src/os/linux/../../common/cmm_cfg.c:264:16: warning: ‘wmode_valid’ defined but not used [-Wunused-function]
 static BOOLEAN wmode_valid(RTMP_ADAPTER *pAd, enum WIFI_MODE wmode)
                ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_wpa.o
/root/src/mt7601/src/os/linux/../../common/cmm_wpa.c: In function ‘PeerPairMsg4Action’:
/root/src/mt7601/src/os/linux/../../common/cmm_wpa.c:1168:11: warning: unused variable ‘group_cipher’ [-Wunused-variable]
  UCHAR    group_cipher = Ndis802_11WEPDisabled;
           ^
/root/src/mt7601/src/os/linux/../../common/cmm_wpa.c: In function ‘PeerGroupMsg2Action’:
/root/src/mt7601/src/os/linux/../../common/cmm_wpa.c:1530:11: warning: unused variable ‘group_cipher’ [-Wunused-variable]
  UCHAR    group_cipher = Ndis802_11WEPDisabled; 
           ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_radar.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/spectrum.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/rtmp_timer.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/rt_channel.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_profile.o
/root/src/mt7601/src/os/linux/../../common/cmm_profile.c: In function ‘rtmp_read_multest_from_file’:
/root/src/mt7601/src/os/linux/../../common/cmm_profile.c:2671:23: warning: unused variable ‘pWdsEntry’ [-Wunused-variable]
  PRT_802_11_WDS_ENTRY pWdsEntry;
                       ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_asic.o
/root/src/mt7601/src/os/linux/../../common/cmm_asic.c: In function ‘AsicAddPairwiseKeyEntry’:
/root/src/mt7601/src/os/linux/../../common/cmm_asic.c:2126:9: warning: unused variable ‘CipherAlg’ [-Wunused-variable]
  UCHAR  CipherAlg = pCipherKey->CipherAlg;
         ^
/root/src/mt7601/src/os/linux/../../common/cmm_asic.c:2123:11: warning: unused variable ‘pKey’ [-Wunused-variable]
  PUCHAR   pKey = pCipherKey->Key;
           ^
  CC [M]  /root/src/mt7601/src/os/linux/../../common/scan.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/cmm_cmd.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/uapsd.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/ps.o
  CC [M]  /root/src/mt7601/src/os/linux/../../rate_ctrl/ra_ctrl.o
/root/src/mt7601/src/os/linux/../../rate_ctrl/ra_ctrl.c: In function ‘MlmeRALog’:
/root/src/mt7601/src/os/linux/../../rate_ctrl/ra_ctrl.c:1603:17: warning: unused variable ‘csd’ [-Wunused-variable]
   BOOLEAN stbc, csd=FALSE;
                 ^
  CC [M]  /root/src/mt7601/src/os/linux/../../rate_ctrl/alg_legacy.o
  CC [M]  /root/src/mt7601/src/os/linux/../../rate_ctrl/alg_ags.o
  CC [M]  /root/src/mt7601/src/os/linux/../../chips/rtmp_chip.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/txpower.o
  CC [M]  /root/src/mt7601/src/os/linux/../../mac/rtmp_mac.o
  CC [M]  /root/src/mt7601/src/os/linux/../../mgmt/mgmt_hw.o
  CC [M]  /root/src/mt7601/src/os/linux/../../mgmt/mgmt_entrytb.o
  CC [M]  /root/src/mt7601/src/os/linux/../../phy/rtmp_phy.o
/root/src/mt7601/src/os/linux/../../phy/rtmp_phy.c: In function ‘NICInitBBP’:
/root/src/mt7601/src/os/linux/../../phy/rtmp_phy.c:61:8: warning: unused variable ‘R0’ [-Wunused-variable]
  UCHAR R0 = 0xff;
        ^
  CC [M]  /root/src/mt7601/src/os/linux/../../phy/rlt_phy.o
  CC [M]  /root/src/mt7601/src/os/linux/../../phy/rlt_rf.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/ba_action.o
  CC [M]  /root/src/mt7601/src/os/linux/../../mgmt/mgmt_ht.o
  CC [M]  /root/src/mt7601/src/os/linux/../../common/rt_os_util.o
  CC [M]  /root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.o
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2380:2: error: unknown field ‘private’ specified in initializer
  .private = (iw_handler *) rt_priv_handlers,
  ^
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2380:2: warning: initialization from incompatible pointer type [enabled by default]
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2380:2: warning: (near initialization for ‘rt28xx_iw_handler_def.get_wireless_stats’) [enabled by default]
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2381:2: error: unknown field ‘num_private’ specified in initializer
  .num_private  = N(rt_priv_handlers),
  ^
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2381:2: warning: excess elements in struct initializer [enabled by default]
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2381:2: warning: (near initialization for ‘rt28xx_iw_handler_def’) [enabled by default]
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2382:2: error: unknown field ‘private_args’ specified in initializer
  .private_args = (struct iw_priv_args *) privtab,
  ^
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2382:26: warning: excess elements in struct initializer [enabled by default]
  .private_args = (struct iw_priv_args *) privtab,
                          ^
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2382:26: warning: (near initialization for ‘rt28xx_iw_handler_def’) [enabled by default]
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2383:2: error: unknown field ‘num_private_args’ specified in initializer
  .num_private_args = N(privtab),
  ^
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2383:2: warning: excess elements in struct initializer [enabled by default]
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2383:2: warning: (near initialization for ‘rt28xx_iw_handler_def’) [enabled by default]
scripts/Makefile.build:257: recipe for target '/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.o' failed
make[2]: *** [/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.o] Error 1
Makefile:1373: recipe for target '_module_/root/src/mt7601/src/os/linux' failed
make[1]: *** [_module_/root/src/mt7601/src/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-3.17.7-gentoo'
Makefile:394: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2

The other commands:
make clean
cp -f os/linux/Makefile.clean os/linux/Makefile
make -C os/linux clean
make[1]: Entering directory '/root/src/mt7601/src/os/linux'
rm -f ../../common/*.o
rm -f ../../common/.*.cmd .*.flags .*.d
rm -f ../../os/linux/*.o *.ko *.mod.o *.mod.c
rm -f ../../os/linux/.*.cmd .*.flags .*.d
rm -fr ../../os/linux/.tmp_versions
rm -f ../../os/linux/Module.symvers
rm -f ../../os/linux/Modules.symvers
rm -f ../../os/linux/Module.markers
rm -f ../../os/linux/modules.order
rm -f ../../chips/*.o
rm -f ../../chips/.*.cmd .*.flags .*.d
rm -f ../../rate_ctrl/*.o
rm -f ../../rate_ctrl/.*.cmd .*.flags .*.d
rm -f ../../ate/common/*.o
rm -f ../../ate/common/.*.cmd .*.flags .*.d
rm -f ../../ate/chips/*.o
rm -f ../../ate/chips/.*.cmd .*.flags .*.d
rm -f ../../phy/*.o
rm -f ../../phy/.*.cmd .*.flags .*.d
rm -f ../../mac/*.o
rm -f ../../mac/.*.cmd .*.flags .*.d
rm -f ../../mcu/*.o
rm -f ../../mcu/.*.cmd .*.flags .*.d
rm -f ../../mgmt/*.o
rm -f ../../mgmt/.*.cmd .*.flags .*.d
rm -f ../../naf/*.o
rm -f ../../naf/.*.cmd .*.flags .*.d
rm -f ../../sta/*.o
rm -f ../../sta/.*.cmd .*.flags .*.d
make[1]: Leaving directory '/root/src/mt7601/src/os/linux'
rm -rf os/linux/Makefile

Thanks


cp -f os/linux/Makefile.6 /root/src/mt7601/src/github/porjo/mt7601/src/os/linux/Makefile
cp: cannot create regular file ‘/root/src/mt7601/src/github/porjo/mt7601/src/os/linux/Makefile’: No such file or directory

**Comment by porjo** [comment]
OK, the relevant errors are these
```
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2380:2: error: unknown field ‘private’ specified in initializer
  .private = (iw_handler *) rt_priv_handlers,
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2381:2: error: unknown field ‘num_private’ specified in initializer
  .num_private  = N(rt_priv_handlers),
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2382:2: error: unknown field ‘private_args’ specified in initializer
  .private_args = (struct iw_priv_args *) privtab,
/root/src/mt7601/src/os/linux/../../os/linux/sta_ioctl.c:2383:2: error: unknown field ‘num_private_args’ specified in initializer
  .num_private_args = N(privtab),
```

I did a quick search and found this post which suggests that it relates to the way your kernel has been compiled, specifically without `wext` support (wireless extensions):

http://rt2x00.serialmonkey.com/pipermail/users_rt2x00.serialmonkey.com/2013-January/005581.html

Unfortunately, I don't have any experience with kernel compilation. You may need to seek assistance from the Gentoo community.

**Comment by lexa2** [comment]
I might be wrong but as far as I remember correctly there's a way to disable wext usage by the driver:
```
3> In os/linux/config.mk
        define the GCC and LD of the target machine
        define the compiler flags CFLAGS
        modify to meet your need.
        ** Build for being controlled by NetworkManager or wpa_supplicant wext functions
           Please set 'HAS_WPA_SUPPLICANT=y' and 'HAS_NATIVE_WPA_SUPPLICANT_SUPPORT=y'.
           => #>cd wpa_supplicant-x.x
           => #>./wpa_supplicant -Dwext -ira0 -c wpa_supplicant.conf -d
        ** Build for being controlled by WpaSupplicant with Ralink Driver
           Please set 'HAS_WPA_SUPPLICANT=y' and 'HAS_NATIVE_WPA_SUPPLICANT_SUPPORT=n'.
           => #>cd wpa_supplicant-0.5.7
           => #>./wpa_supplicant -Dralink -ira0 -c wpa_supplicant.conf -d
```

**Comment by pmam2** [comment]
quite frustrating... as you may see I do have wext:
zgrep -i wext /proc/config.gz
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_CFG80211_WEXT=y

 I also set: HAS_NATIVE_WPA_SUPPLICANT_SUPPORT=n and still can not compile.
Any other idea?

**Comment by porjo** [comment]
It looks like you need `CONFIG_WEXT_PRIV=y` in particular.  See this post:
http://rt2x00.serialmonkey.com/pipermail/users_rt2x00.serialmonkey.com/2013-January/005585.html

@lexa2 My reading of that part of the README is that you are not disabling `wext` by making that change but just defining which provider to use.

**Comment by pmam2** [comment]
porjo Hi,
I found out how to activate wext_priv and other parameters in kernel menuconfig -
I followed to the next discussions in the link that you pointed me to and find this:
http://rt2x00.serialmonkey.com/pipermail/users_rt2x00.serialmonkey.com/2013-January/005587.html
So, when I add Cisco/Aironet module (M) and compiled the kernel, I got:
zgrep -i wext /proc/config.gz
CONFIG_WEXT_CORE=y
CONFIG_WEXT_PROC=y
CONFIG_WEXT_SPY=y
CONFIG_WEXT_PRIV=y
CONFIG_CFG80211_WEXT=y
Then I could compile without errors and now I have ra0 interface :) 
ra0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.186.118  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::24b:5bfc:8a9e:b148  prefixlen 64  scopeid 0x20<link>
        ether 00:22:c0:31:44:20  txqueuelen 1000  (Ethernet)
        RX packets 63623  bytes 15767178 (15.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0 
Now I need to see how to connect to network.

Thanks a lot

**Comment by porjo** [comment]
Thanks for the update. I'll add a note to the README for other Gentoo users.
