### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by fonini** [porjo/mt7601#6]
Hi porjo,

I'm trying to compile the driver on my Raspberry, but I'm getting some errros.
I posted the errors on Pastebin to make easier for you to read.

http://pastebin.com/AqWbRNcV

I've already installed the kernel headers for 3.15.8+.

My uname -a output:
Linux xbian.private 3.15.8+ #6 Wed Oct 8 06:31:51 CEST 2014 armv6l GNU/Linux

Thanks in advance!

**Comment by porjo** [comment]
Thanks for reporting. Try again now. You will need to run `git pull` first.

The last commit included something that shouldn't have been there! I've rolled that back now.

**Comment by fonini** [comment]
Thank you, I'm travelling right now, but I'll test ASAP.

**Comment by porjo** [comment]
This should be fixed. Please leave a note here if you continue to see problems.
